% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}


\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{apalike}
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Statistics Taster Session},
  pdfauthor={Prof Peter Neal},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Statistics Taster Session}
\author{Prof Peter Neal}
\date{University of Nottingham}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\begin{verbatim}
## Linking to ImageMagick 6.9.12.3
## Enabled features: cairo, freetype, fftw, ghostscript, heic, lcms, pango, raw, rsvg, webp
## Disabled features: fontconfig, x11
\end{verbatim}

\hypertarget{preliminaries}{%
\chapter*{Preliminaries}\label{preliminaries}}
\addcontentsline{toc}{chapter}{Preliminaries}

Welcome to the free Statistics Taster Session.

\hypertarget{stats_taster}{%
\chapter{Statistics Taster Session}\label{stats_taster}}

\hypertarget{sec_intro}{%
\section{Introduction}\label{sec_intro}}

This statistics taster session provides a brief introduction to the concept of maximum likelihood estimation. This introduction is motivated by the \href{https://en.wikipedia.org/wiki/Reed\%E2\%80\%93Frost_model}{Reed-Frost} epidemic model and is applied to household data collected from measles outbreak in Providence, Rhode Island between 1929-1934, see
\href{https://www.jstor.org/stable/984949\#metadata_info_tab_contents}{Wilson \emph{et al.} (1939)} (also
Bailey (1975), pages 249-254). We describe how the Reed-Frost model is defined in terms of the probability \(p\) that an individual, whilst infectious, will infect a susceptible individual they live with. We explore how to choose \(p\) given the data in a principled manner, and in particular, to use \protect\hyperlink{sec_like}{Maximum Likelihood Estimation} to find the value of \(p\) which maximises the probability of the observed data occurring. We discuss briefly the concept of \protect\hyperlink{sec_GoF}{goodness-of-fit} and the question does the Reed-Frost model provide a good fit to the data? The mathematical concepts introduced in this session are explored further in the Foundations of Statistics module in the \href{https://www.nottingham.ac.uk/pgstudy/course/taught/statistical-science-distance-learning-msc}{MSc in Statistical Science (Distance Learning)}.

\hypertarget{sec_ReedFrost}{%
\section{Reed-Frost Model}\label{sec_ReedFrost}}

The Reed-Frost model makes the following assumptions for the spread of the disease through a community.

The Reed-Frost model is an example of an \(SIR\) epidemic model. That is,
individuals are assumed to be in one of three states:

\begin{itemize}
\tightlist
\item
  {\textbf{Susceptible}} - susceptible to being infected with the disease.\\
\item
  {\textbf{Infective}} - infected with the disease and are able to infect susceptible individuals.\\
\item
  \textbf{Removed} - individuals who are no longer infectious, for example, recovered or dead, and who cannot be reinfected.
\end{itemize}

The only transitions in state in an \(SIR\) epidemic model are:\\

\[ \mbox{Susceptible} \longrightarrow \mbox{Infective} \]

and

\[ \mbox{Infective} \longrightarrow \mbox{Removed}. \]

The Reed-Frost model models the spread of the disease on a discrete time basis with each individual infectious for one time unit only. The time units are sometimes referred to as generations since an individual infectious at time \(t\) (generation \(t\)) will have been infected by an individual infectious at time \(t-1\) (generation \(t-1\)). It is assumed that each infectious individual has probability \(p\) of making an infectious contact with a given susceptible, and the number of individuals an infectious individual makes contact with in a group of \(s\) susceptibles follows a Binomial distribution with parameters \(s\) and \(p\) (\({\rm Bin} (s,p)\)). That is, if \(s=2\), there are 2 susceptible individuals the probability an infective makes infectious contact with only one of the two susceptible individuals is

\[2 p (1-p). \]

\hypertarget{households-of-size-3}{%
\subsection*{Households of size 3}\label{households-of-size-3}}
\addcontentsline{toc}{subsection}{Households of size 3}

We illustrate how the Reed-Frost model works in households of size 3. Suppose that we have {one initial infective} and {two initial susceptibles}. The initial individual can infect 0, 1 or 2 of the initial susceptibles and these occur with probabilities \((1-p)^2\), \(2 p (1-p)\) and \(p^2\), respectively. In the event that the initial infective infects one of the susceptibles after one time unit we have a situation where there is one infective, one susceptible and one removed individual in the household. There is then probability \(p\) that the infective will infect the remaining susceptible and probability \(1-p\) that the susceptible will avoid infection.

The four possible outcomes for a disease outbreak in a household of size 3 and these are presented in Figure \ref{fig:RFoutcome}. The red individual denotes the initial infective, the green individuals denote those individuals who remain susceptible throughout the outbreak and the blue individuals are those individuals who start susceptible but become infected in the epidemic.

\begin{figure}
\includegraphics[width=0.8\linewidth]{RF} \caption{ Possible outcomes in a household of size 3.}\label{fig:RFoutcome}
\end{figure}

A summary of the four possible outcomes and the probability of each outcome is given in the table below.

\begin{longtable}[]{@{}llc@{}}
\toprule\noalign{}
Outcome & No.~infected & Probability \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
A & 1 & \((1-p)^2\) \\
B & 2 & \(2p(1-p)^2\) \\
C & 3 & \(p^2\) \\
D & 3 & \(2p^2(1-p)\) \\
\end{longtable}

We note that both outcomes \(C\) and \(D\) lead to all 3 individuals being infected. Therefore if we cannot distinguish between the ways in which the epidemic takes place in a household but only classify an outbreak by its final size, the total number infected, we have that:

\begin{longtable}[]{@{}lc@{}}
\toprule\noalign{}
Final Size & Probability \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
1 & \((1-p)^2\) \\
2 & \(2p(1-p)^2\) \\
3 & \(p^2(3-2p)\) \\
\end{longtable}

For example, if \(p=0.4\), there is probability \(0.6^2 = 0.36\) that the initial infective does not infect either remaining susceptible and the final size of the epidemic is 1. There is probability \(2 (0.4) 0.6^2 = 0.288\) that the final size of the epidemic is 2. That is, the initial infective infects one of the initial susceptibles who in turn fails to infect the third person in the household. Finally, there is probability \(0.4^2 (3-2\times 0.4) = 0.352\) that all 3 individuals in the household are infected.

\hypertarget{sec_data}{%
\section{Data}\label{sec_data}}

We apply the Reed-Frost model to the measles outbreaks in Providence, Rhode Island. The data were first reported in \href{https://www.jstor.org/stable/984949\#metadata_info_tab_contents}{Wilson \emph{et al.} (1939)} and investigated further in Bailey (1975). The data we consider here are measles outbreaks in 334 households of size 3.

\begin{longtable}[]{@{}lr@{}}
\toprule\noalign{}
Final Size & Observed \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
1 & 34 \\
2 & 25 \\
3 & 275 \\
\end{longtable}

\hypertarget{sec_like}{%
\section{Likelihood}\label{sec_like}}

{\textbf{What is the probability (likelihood) that we observe the Providence data under the assumption of the Reed-Frost model?}}\\
This is an example of a \protect\hyperlink{def:multinomial}{multinomial distribution}.

\leavevmode\vadjust pre{\hypertarget{def:multinomial}{}}%
{\textbf{Multinomial Distribution}}\\
Suppose that there are \(K\) possible mutually exclusive outcomes for an experiment. For \(i=1,2,\ldots,K\), let \(q_i\) denote the probability that outcome \(i\) occurs with \(\sum_{i=1}^K q_i = 1\).

Suppose that \(n\) independent replicates of the experiment are performed. For \(i=1,2,\ldots,K\), let \(n_i\) denote the number of occurrences of outcome \(i\) with \(\sum_{i=1}^K n_i = n\).

Then the probability of observing \(\mathbf{n} =(n_1, n_2, \ldots, n_K)\) is:

\[ \frac{n!}{n_1! n_2! \ldots n_K!} q_1^{n_1} q_2^{n_2} \ldots q_K^{n_K}.\]

Note that the special case \(K=2\) corresponds to the binomial distribution.

For an epidemic outbreak in a household of size 3, we have \(K=3\) possible outcomes corresponding to epidemics of final size 1, 2 and 3 with probabilities \(q_1 = (1-p)^2\), \(q_2 = 2p(1-p)^2\) and \(q_3 = p^2 (3-2p)\), respectively. Note the probabilities \(q_1\), \(q_2\) and \(q_3\) are all functions of the probability \(p\) of an infective infecting a susceptible.

Thus the likelihood of observing the data \(\mathbf{n} = (n_1, n_2, n_3) = (34,25,275)\) as a function of the infection probability \(p\), which we denote \(L (p; \mathbf{n})\) is given by

\begin{eqnarray*}
L(p; \mathbf{n}) &=& \frac{n!}{n_1! n_2! n_3!} \left[ (1-p)^2 \right]^{n_1} \left[ 2 p (1-p)^2 \right]^{n_2} \left[ p^2(3- 2p) \right]^{n_3} \\
&=& \frac{n!}{n_1! n_2! n_3!} 2^{n_2} p^{n_2 + 2 n_3} (1-p)^{2(n_1 + n_2)} (3-2p)^{n_3} \\
&=& 2.5037 \times 10^{90} p^{575} (1-p)^{118} (3-2p)^{275}.
\end{eqnarray*}

{\textbf{What value of \(p\) maximises \(L(p; \mathbf{n})\)?}}

By plotting \(L(p; \mathbf{n})\) as a function of \(p\) in Figure \ref{fig:RFlike} we observe that \(L(p;\mathbf{n})\) obtains its maximum at a value of \(p\) close to 0.7. We can find \(\hat{p}\) which maximises the likelihood by solving
\[ \frac{d \;}{dp}L(p; \mathbf{n})=0. \]

\begin{figure}
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/RFlike-1} \caption{Likelihood for the Providence data.}\label{fig:RFlike}
\end{figure}

It is however easier to work with \(\ell (p; \mathbf{n}) = \log L (p; \mathbf{n})\), the log-likelihood, and find the value of \(p\) which maximises \(\ell (p; \mathbf{n})\). The reasons for using the log-likelihood include:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Log(arithm) is an increasing function such that \(0< x <y\) if and only if \(\log (x) < \log (y)\). Therefore the value of \(p\) which maximises the log-likelihood will also maximise the likelihood.\\
\item
  It is usually easier to differentiate the log-likelihood than the likelihood making it {\textbf{mathematically}} preferable.\\
\item
  The log-likelihood is more numerically stable than the likelihood making it {\textbf{computationally}} preferable.
\end{enumerate}

In Figure \ref{fig:RFloglike}, we plot the log-likelihood \(\ell (p; \mathbf{n})\) for the Providence data set for \(p\) on the range \(0.4 < p < 0.99\). We observe that \(\ell (p; \mathbf{n})\) obtains its maximum for \(p\) close to 0.7.

\begin{figure}
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/RFloglike-1} \caption{Likelihood for the Providence data.}\label{fig:RFloglike}
\end{figure}

A numerical optimisation method, such as the \href{https://en.wikipedia.org/wiki/Golden-section_search}{Golden Section Method}, can be used to find \(\hat{p}\) but we outline how to obtain \(\hat{p}\) algebraically.

Watch \protect\hyperlink{video}{Video} for a derivation of the maximum likelihood estimator of \(p\).

\leavevmode\vadjust pre{\hypertarget{video}{}}%
{\textbf{Video: Derivation of \(\hat{p}\).}}

Alternatively workings are available:

\textbf{Derivation of \(\hat{p} =0.7279\).}

Let \(A = 2.5037 \times 10^{90}\), then \(\ell (p; \mathbf{n}) = \log L (p; \mathbf{n})\) is given by

\begin{eqnarray}
\ell (p; \mathbf{n}) &=& \log \left[ 2.5037 \times 10^{90} p^{575} (1-p)^{118} (3-2p)^{275} \right] \\
&=& \log A + \log \left( p^{575}\right) + \log \left((1-p)^{118} \right) + \log \left((3-2p)^{275} \right) \\
&=& \log A + 575 \log (p) + 118 \log (1-p) + 275 \log (3-2p).
\end{eqnarray}

To find \(\hat{p}\), we solve

\[ \frac{d \;}{dp}\ell(p; \mathbf{n})=0. \]

Note that this will give a turning point in \(\ell(p; \mathbf{n})\) and we need to check that this is a maximum. This can be done by studying the sign of the second derivative, \(\frac{d^2 \;}{dp^2}\ell(p; \mathbf{n})\), or by plotting the likelihood in the vicinity of \(\hat{p}\).

Thus \(\hat{p}\) solves

\begin{eqnarray}
\frac{575}{p} + \frac{118(-1)}{1-p} + \frac{275(-2)}{3-2p} &=& 0 \\
575 (1-p)(3-2p) -118 p (3-2p) - 550 p (1-p) &=& 0 \\
1936 p^2 -3779 p + 1725 &=& 0.
\end{eqnarray}

There are two solutions to the quadratic \(1936 p^2 - 3779 p + 1725 =0\) and these are

\[ p = \frac{3779 \pm \sqrt{(-3779)^2-4 \times 1936 \times 1725}}{2 \times 1936} = 1.224 \mbox{ or } 0.7279. \]

Since \(p\) is a probability (between 0 and 1), we have that \(\hat{p} = 0.7279\).

\hypertarget{sec_GoF}{%
\section{Goodness-of-fit}\label{sec_GoF}}

We have found the MLE, \(\hat{p}\), which maximises the likelihood of the observed data under the assumption of the Reed-Frost model. However, an important question is:

{\textbf{Is the Reed-Frost model actually a good model for the Providence data set?}}

We can use the MLE, \(\hat{p}\) to answer this question. If the Reed-Frost model with \(p = 0.7279\) is appropriate for the Providence data, we would expect to observe the proportion of households with final size 1, 2 and 3 to be \(0.0740 (=(1-p)^2)\), \(0.1078 (=2 p (1-p)^2)\) and \(0.8182 (=p^2 (3-2p))\), respectively. Thus the expected number of households for each final size amongst \(n=334\) households of size 3 are:

\begin{longtable}[]{@{}lrl@{}}
\toprule\noalign{}
Final Size & Expected & Expected formula \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
1 & 24.73 & \(n(1-p)^2 =334 (1-0.7279)^2\) \\
2 & 36.00 & \(n [2 p(1-p)^2] =334 \left[2 \times 0.7279 (1-0.7279)^2 \right]\) \\
3 & 273.27 & \(n p^2 (3-2p) =334 \times0.7279^2 (3 - 2 \times 0.7279)\) \\
\end{longtable}

The Reed-Frost model is a good fit for data if the observed number of households of each final size are \emph{close} to the expected number of households of each final size. This raises the question of how we measure closeness, and consequently, the goodness-of-fit of the Reed-Frost model for the Providence data? We present the answer without going into the statistical details behind the goodness-of-fit statistic which is covered in the Foundations of Statistics module.

For \(i=1, 2, 3\), let \(O_i\) and \(E_i\) denote the observed and expected number of households with final size \(i\). We compute the test statistic:

\[ T = \sum_{i=1}^3 \frac{(O_i -E_i)^2}{E_i}. \]

The smaller (closer to 0) the test statistic \(T\) is, the better the Reed-Frost model is at fitting the data.
Formally, we test the null hypothesis:

\[ H_0: \mbox{The Reed-Frost model provides a good model for the data} \]

versus the alternative hypothesis:

\[ H_1: \mbox{The Reed-Frost model does not provides a good model for the data} \]

Under the null hypothesis the test statistic, \(T\), follows a \href{https://en.wikipedia.org/wiki/Chi-squared_distribution}{\(\chi\)-square distribution} with 1 degree of freedom.

The test statistic for the Providence data is

\[ T = \frac{(34- 24.73)^2}{24.73} +  \frac{(25- 36.00)^2}{36.00} +  \frac{(275- 273.27)^2}{273.27} = 20.33. \]

The probability of a \(\chi\)-square distribution distribution with 1 degree of freedom taking a value greater than or equal to \(20.33\) is \(6.52 \times 10^{-6}\). That is, there is about a 1 in 150,000 chance of observing a test statistic \(T\) as large as 20.33 if the null hypothesis were true. This is highly unlikely, and hence, we reject the Reed-Frost model as a good model for the measles outbreak in Providence.

\hypertarget{sec_shiny}{%
\section{Shiny App}\label{sec_shiny}}

The \href{https://shiny.maths.nottingham.ac.uk/pmzpn/ReedFrost/}{Reed-Frost} R Shiny app allows you to explore the likelihood and goodness-of-fit for the Reed-Frost model applied to different datasets \(\mathbf{n}= (n_1,n_2,n_3)\) of epidemic outbreaks in households of size 3. The default data is the Providence data set.

In the R Shiny app there are three options for plotting the likelihood. The likelihood, log-likelihood or relative likelihood can be plotted. The relative likelihood is on a scale 0 to 1 and is given by the likelihood divided by the maximum value the likelihood obtains. Thus the plot of the relative likelihood is identical to the plot of the likelihood except the labeling on the \(y\)-axis. The reason for including the relative likelihood is, that for large \(n\), the likelihood can be very small and equal to 0 for computer accuracy. However, exploiting the log-likelihood we can compute and plot the relative likelihood.

\hypertarget{extensions}{%
\section{Extensions}\label{extensions}}

In this illustrative example we have assumed all households are of size 3. It is straightforward, at least in principle, to allow for households of different sizes. Allowing for larger household sizes in the data makes the likelihood more complex and results in a quintic (order 5) polynomial in the case of households of size 4. Therefore for larger households numerical methods are required to find the maximum likelihood estimator.

The Reed-Frost model makes the assumption that whether or not an infective infects a susceptible is \textbf{independent} of whether or not the infective infects another susceptible in their household. However, we might very well expect these two events to be \textbf{dependent} as the probability an infective infects susceptibles could depend on the severity of their case of the disease. Alternative epidemic models such as the general stochastic epidemic model allow for dependence between the probability of infecting different individuals by conditioning the probability of infection on the length of an individual's infectious period.

\hypertarget{references}{%
\subsection*{References}\label{references}}
\addcontentsline{toc}{subsection}{References}

Bailey, N.T.J. (1975) \emph{The Mathematical Theory of Infectious Diseases and Its Applications.} \(2^{nd}\) edition. Griffin, London.

\href{https://www.jstor.org/stable/984949\#metadata_info_tab_contents}{Wilson, E.B., Bennett, C., Allen, M. and Worcester, J. (1939)} Measles and Scarlet Fever in Providence, R. I., 1929-1934 with respect to Age and Size of Family. \emph{Proc. Amer. Phil. Soc.} \textbf{80} 357-476.

  \bibliography{book.bib,packages.bib}

\end{document}
